//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OryxBot.Client.Windows.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIApplicationContext {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIApplicationContext() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OryxBot.Client.Windows.Resources.UIApplicationContext", typeof(UIApplicationContext).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        internal static string ErrorMessage_Http {
            get {
                return ResourceManager.GetString("ErrorMessage.Http", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is no longer subscribed!.
        /// </summary>
        internal static string ErrorMessage_NoLongerSubscribed {
            get {
                return ResourceManager.GetString("ErrorMessage.NoLongerSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please extend your subscription to resume..
        /// </summary>
        internal static string ErrorMessage_PleaseExtend {
            get {
                return ResourceManager.GetString("ErrorMessage.PleaseExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OryxBot.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Recording Route (F1).
        /// </summary>
        internal static string ToolStipToggleBotTradeMissionRecordButton_TextStart {
            get {
                return ResourceManager.GetString("ToolStipToggleBotTradeMissionRecordButton.TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording Route (F1).
        /// </summary>
        internal static string ToolStipToggleBotTradeMissionRecordButton_TextStop {
            get {
                return ResourceManager.GetString("ToolStipToggleBotTradeMissionRecordButton.TextStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Trade Mission (F2).
        /// </summary>
        internal static string ToolStipToggleBotTradeMissionRunButton_TextStart {
            get {
                return ResourceManager.GetString("ToolStipToggleBotTradeMissionRunButton.TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Trade Mission (F2).
        /// </summary>
        internal static string ToolStipToggleBotTradeMissionRunButton_TextStop {
            get {
                return ResourceManager.GetString("ToolStipToggleBotTradeMissionRunButton.TextStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Logged In.
        /// </summary>
        internal static string ToolStipUsernameLabel_Text {
            get {
                return ResourceManager.GetString("ToolStipUsernameLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as :name.
        /// </summary>
        internal static string ToolStipUsernameLabel_TextLoggedInAs {
            get {
                return ResourceManager.GetString("ToolStipUsernameLabel.TextLoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ToolStripCloseButton_Text {
            get {
                return ResourceManager.GetString("ToolStripCloseButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Custom Routes.
        /// </summary>
        internal static string ToolStripEnableCustomRoutesButton_Text {
            get {
                return ResourceManager.GetString("ToolStripEnableCustomRoutesButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Custom Routes.
        /// </summary>
        internal static string ToolStripEnableCustomRoutesButton_Text_Custom {
            get {
                return ResourceManager.GetString("ToolStripEnableCustomRoutesButton.Text_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Route File.
        /// </summary>
        internal static string TradeMissionRunRouteFile_Title {
            get {
                return ResourceManager.GetString("TradeMissionRunRouteFile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Route.
        /// </summary>
        internal static string TradeMissionSaveRouteFile_Title {
            get {
                return ResourceManager.GetString("TradeMissionSaveRouteFile.Title", resourceCulture);
            }
        }
    }
}
