<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>Bot</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Albion.Network" Version="5.0.0" />
      <PackageReference Include="MouseKeyHook" Version="5.6.0" />
      <PackageReference Include="SharpPcap" Version="5.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OryxBot.Albion\OryxBot.Albion.csproj" />
      <ProjectReference Include="..\OryxBot.Shared\OryxBot.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Services\NewCharacterEventHandler.cs">
        <DependentUpon>NetworkDataProvider.cs</DependentUpon>
      </Compile>
      <Compile Update="Services\RaiseEvents.cs">
        <DependentUpon>NetworkDataProvider.cs</DependentUpon>
      </Compile>
      <Compile Update="Services\MoveEventHandler.cs">
        <DependentUpon>NetworkDataProvider.cs</DependentUpon>
      </Compile>
      <Compile Update="TradeMissionRecordState.cs">
        <DependentUpon>TradeMissionRecord.cs</DependentUpon>
      </Compile>
      <Compile Update="RecordableStep.cs">
        <DependentUpon>TradeMissionRecord.cs</DependentUpon>
      </Compile>
      <Compile Update="TradeMissionRunRoute.cs">
        <DependentUpon>TradeMissionRun.cs</DependentUpon>
      </Compile>
      <Compile Update="TradeMissionTakeQuest.cs">
        <DependentUpon>TradeMissionRun.cs</DependentUpon>
      </Compile>
      <Compile Update="TradeMissionBank.cs">
        <DependentUpon>TradeMissionRun.cs</DependentUpon>
      </Compile>
      <Compile Update="TradeMissionMovementTracker.cs">
        <DependentUpon>TradeMissionRun.cs</DependentUpon>
      </Compile>
      <Compile Update="TradeMissionProgressQuest.cs">
        <DependentUpon>TradeMissionRun.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\route_lymhurst_bank_to_quest.csv" />
      <EmbeddedResource Include="Resources\route_lymhurst_quest_to_bank.csv" />
      <EmbeddedResource Include="Resources\route_lymhurst_trademission.csv" />
      <EmbeddedResource Include="Resources\route_lymhurst_trademission_back.csv" />
    </ItemGroup>

</Project>
