<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net5.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <Nullable>enable</Nullable>
        <Company>OryxBot</Company>
        <Product>OryxBot</Product>
        <NeutralLanguage>en</NeutralLanguage>
        <AssemblyName>OryxBot</AssemblyName>
        <ApplicationIcon>./../Resources/oryx_icon_small_colored.ico</ApplicationIcon>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
        <HintPath>C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\OryxBot.Albion\OryxBot.Albion.csproj" />
      <ProjectReference Include="..\OryxBot.Shared\OryxBot.Shared.csproj" />
        <PackageReference Include="Albion.Network" Version="5.0.0" />
        <PackageReference Include="MouseKeyHook" Version="5.6.0" />
        <PackageReference Include="SharpPcap" Version="5.4.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Kernel.cs">
        <DependentUpon>Program.cs</DependentUpon>
      </Compile>
      <Compile Update="Resources\UIApplicationContext.Designer.cs">
        <AutoGen>True</AutoGen>
        <DependentUpon>ApplicationContext.resx</DependentUpon>
        <DesignTime>True</DesignTime>
      </Compile>
      <Compile Update="MainForm.Designer.cs">
        <DependentUpon>MainForm.cs</DependentUpon>
      </Compile>
      <Compile Update="MainForm.Domain.cs">
        <DependentUpon>MainForm.cs</DependentUpon>
      </Compile>
      <Compile Update="MainFormToolstrip.cs">
        <DependentUpon>MainForm.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\UIApplicationContext.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>UIApplicationContext.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="MainForm.resx">
        <DependentUpon>MainForm.cs</DependentUpon>
      </EmbeddedResource>
      <EmbeddedResource Include="Bot\Resources\route_lymhurst_bank_to_quest.csv" />
      <EmbeddedResource Include="Bot\Resources\route_lymhurst_quest_to_bank.csv" />
      <EmbeddedResource Include="Bot\Resources\route_lymhurst_trademission.csv" />
      <EmbeddedResource Include="Bot\Resources\route_lymhurst_trademission_back.csv" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="InputSimulatorPlus" Version="1.0.7" />
      <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
      <PackageReference Include="NLog" Version="4.7.7" />
    </ItemGroup>

    <ItemGroup>
      <None Update="NLog.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties" />
    </ItemGroup>

</Project>