name: dotnet package

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Build .NET application for Linux
        run: dotnet build --configuration Release --runtime linux-x64 --self-contained false OryxBot.Client.Linux
        
      - name: Compress build files to oryxbot.tar.gz
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: "${{ github.workspace }}/OryxBot.Client.Linux/bin/Release/net7.0/linux-x64"
          files: "."
          outPath: "${{ github.workspace }}/oryxbot.tar.gz"
          
      - name: Send oryxbot.tar.gz to live oryxbot.com server
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://oryxbot.com/deploy/oryxbot'
          method: 'POST'
          bearerToken: '***REMOVED***'
          files: '{ "file":"${{ github.workspace }}/oryxbot.tar.gz" }'